### PR TITLE
Allow the addFilter commands to accept arrays as input

### PR DESCRIPTION
**Pull request by Gurrt**
I noticed that only the keyword tracking had an option to add multiple keywords to filter at once. I abstracted this logic out of the function and applied it to all possible filters.

### CODE REVIEW

**Comment by nathanbowser** [comment]
This feels like a bloated API to me. What do you think about making a tracking function be able to support a single keyword or multiple?

**Comment by Gurrt** [comment]
You're right, that would be a better solution. See newest commit. While it is now essentially obsolete, I kept the trackMultiple function in there for backwards compatibility. Removed the ones I added in the previous commit though.

**Comment by nathanbowser** [comment]
Merged manually with some minor changes. Thanks!

**Comment by nathanbowser** [comment]
@Gurrt + node-tweet-stream@1.10.0 is on npm

**Pull request closed without merging**
