### PR TITLE
Fix sample code

### PR DESCRIPTION
**Pull request by elisaado**

### CODE REVIEW

**Comment by nathanbowser** [comment]
This is incorrect. The syntax in the readme is fine.

**Comment by elisaado** [comment]
On my side node said that the comma was not correct, I removed the command
and everything worked.

**Comment by elisaado** [comment]
* "Command" should be "comma" (can't edit from here)

**Comment by nathanbowser** [comment]
Weird. Perhaps you had a `;` at the end of the first line?

This is valid syntax:
```javascript
var a = true
  , b = false
```

This is not:
```javascript
var a = true;
  , b = false
```

**Pull request closed without merging**
